feat: add login screen
futuresuper/fs-mobile-app pull request #3
Opened 2022-04-26 00:45 UTC by andrewsel

* Login screen added (not yet connected to api)
* Started structure for managing icons
* Animated logo using React Native `Animated` library
* Layout using `KeyboardAvoidingView` so visible when phone keyboard active

2022-04-27 03:51 UTC, kuhnza requested changes
Looking good mate. Well done on those animations – slick.

A few things to look at but great first cut.

2022-04-27 03:51 UTC, kuhnza commented on src/auth/LoginScreen.tsx
> +const styles = StyleSheet.create({
Can we switch this over to the theme enabled `createStylesheet` function?

It works by passing a function that returns a style object. The function receives the theme object allowing you to substitute theme values like so:

```typescript
const styles = createStylesheet(({ palette, spacing }) => ({
  container: {
    backgroundColor: palette.black,
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingVertical: spacing(15),
    paddingHorizontal: spacing(5)
  },
  // ... snip
});

2022-04-27 03:51 UTC, kuhnza commented on src/auth/LoginScreen.tsx
> +    borderBottomColor: '#FFFFFF',
Replace colour literal with theme value

2022-04-27 03:51 UTC, kuhnza commented on src/auth/LoginScreen.tsx
> +    marginBottom: 6,
Replace padding and margin values with theme `spacing` function value.

2022-04-27 03:51 UTC, kuhnza commented on src/common/Button.tsx
> +const styles = StyleSheet.create({
Replace with `createStylesheet`

2022-04-27 03:51 UTC, kuhnza commented on src/common/Icon.tsx
> +export function User({ size = 40, colour = '#3DFA52' }) {
Rather than hand importing these SVGs we can import them directly via [react-native-svg-transformer](https://github.com/kristerkari/react-native-svg-transformer). Should make them much faster and cleaner to include in the project.

See:
* https://docs.expo.dev/ui-programming/using-svgs/
* https://github.com/kristerkari/react-native-svg-transformer#for-expo-sdk-v4100-or-newer

2022-04-27 03:51 UTC, kuhnza commented on src/common/Icon.tsx
> +export function Shield({ size = 40, colour = '#3DFA52' }) {
Colour literal. Add or reference theme instead

2022-04-27 03:51 UTC, kuhnza commented on src/common/Logo.tsx
> +      <Svg width={size} height={size} viewBox="0 0 128 128" fill="none">
Import SVG from file once transformer is setup.

2022-04-27 03:51 UTC, kuhnza commented on package.json
> +    "@types/react": "^18.0.6",
Any reason for this change? No longer matches React version so may result in runtime errors as compiled types won't match major React version (17).

2022-04-27 03:51 UTC, kuhnza commented on App.tsx
> +  return <LoginScreen />;
When resolving conflict wrap in `ThemeProvider` and leave `StatusBar` component below as sibling.

2022-04-27 03:51 UTC, kuhnza commented on src/auth/LoginScreen.tsx
> +      <StatusBar style="light" />
`StatusBar` should move out into main `App` component unless specifically required to match style for this particular screen

2022-04-27 03:51 UTC, kuhnza commented on src/auth/LoginScreen.tsx
> +            }
Prefer explicit handler function. For example:

```typescript
const handleNoAccount = () => WebBrowser.openBrowserAsync('https://join.futuresuper.com.au')
```

2022-04-27 03:51 UTC, kuhnza commented on src/auth/LoginScreen.tsx
> +          <TextInput
Not necessary for now but let's pair up to factor out input into custom component.

2022-04-28 04:39 UTC, andrewsel commented
@kuhnza all done and ready for review again

2022-04-28 04:43 UTC, kuhnza approved these changes

2022-04-28 04:43 UTC, kuhnza commented on src/common/Button.tsx
> +const styles = StyleSheet.create({
Looks like this one might have been missed?

2022-04-28 04:53 UTC, merged